name: azul_project
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.12.0
  get: ^3.26.0

  dio: ^3.0.10
  flutter_html: ^1.3.0
  intl: ^0.17.0

  shared_preferences: ^2.0.4
  cached_network_image: ^2.5.1
  connectivity: ^3.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: AlJazeera
      fonts:
         - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Bold.ttf
         - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Bold-1.ttf
         - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Light.ttf
         - asset: assets/fonts/ArbFONTS-Al-Jazeera-Arabic-Regular.ttf


